name: Release Deployment

on:
  release:
    types: [ published ]

jobs:
  sentry-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get SENTRY_RELEASE
        run: |
          echo "SENTRY_RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: baryonics@${{env.SENTRY_RELEASE}}